# For changed dependencies
📦 dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - pnpm-lock.yaml

# For changes in documentation
📖 documentation:
  - changed-files:
      - any-glob-to-any-file:
          - docs/*.md
          - docs/**/*.md

# For changes in the site, but not markdown files
🌍 site:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**'

# For changes in the metadata
🫧 metadata:
  - changed-files:
      - any-glob-to-any-file:
          - 'icons/*.json'
          - categories/*

# For changes or added icons
🎨 icon:
  - changed-files:
      - any-glob-to-any-file:
          - 'icons/*.svg'
          - 'business-icons/**/*.svg'
          - 'illustration-icons/**/*.svg'

# For changes in the ycloud package
🧳 ycloud package:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/icons/*'

# For changes in the YCloud React package
⚛️ react package:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/icons-react/*'

# For changes in the YCloud React Native package
⚛️ react native package:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/icons-react-native/*'

# For changes in the YCloud vue packages
💎 vue package:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/icons-vue/*'

# For changes in the YCloud angular package
🅰️ angular package:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/icons-angular/*'

# For changes in the YCloud preact package
⚛️ preact package:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/icons-preact/*'

# For changes in the YCloud svelte package
🧣 svelte package:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/icons-svelte/*'

# For changes in the YCloud solid package
🪝 solid package:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/icons-solid/*'

# For changes in the YCloud astro package
🚀 astro package:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/icons-astro/*'

# For changes in the @ycloud-web/icons-data package
❇️ icons-data package:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/icons-data/*'

# For changes in the YCloud static package
🪨 static package:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/icons-static/*'
