packages:
  - 'apps/*'
  - 'packages/*'
  - 'tools/*'
  - 'docs'

overrides:
  axios: ^1.12.0
  cross-spawn: 7.0.5
  fast-json-patch: ^3.1.1
  form-data: ^4.0.4
  semver: ^7.7.3
  vite-prerender-plugin: 0.5.13
  webpack-dev-middleware: ^5.3.4

peerDependencyRules:
  allowedVersions:
    typescript: 7.0.1-rc

allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  esbuild: false
  lmdb: false
  msgpackr-extract: false
  nice-napi: false
  sharp: false
  svelte-preprocess: false
  ttf2woff2: false
  unrs-resolver: false
  vue-demi: false

minimumReleaseAgeExclude:
  - vite@8.1.0
  - '@vitejs/plugin-react@6.0.3'
