const categoryTitleMap: Record<string, string> = {
  Accessibility: '无障碍',
  'Accounts & access': '账号与访问',
  Animals: '动物',
  Arrows: '箭头',
  Buildings: '建筑',
  Charts: '图表',
  Communication: '沟通',
  Connectivity: '连接',
  Cursors: '光标',
  Design: '设计',
  'Coding & development': '编码与开发',
  Devices: '设备',
  Emoji: '表情',
  'File icons': '文件',
  Finance: '金融',
  'Food & beverage': '餐饮',
  Gaming: '游戏',
  Home: '家居',
  Layout: '布局',
  Mail: '邮件',
  Mathematics: '数学',
  Medical: '医疗',
  Multimedia: '多媒体',
  Nature: '自然',
  'Navigation & Places': '导航与地点',
  Notification: '通知',
  People: '人物',
  Photography: '摄影',
  Science: '科学',
  Seasons: '季节',
  Security: '安全',
  Shapes: '形状',
  Shopping: '购物',
  Social: '社交',
  Sports: '运动',
  Sustainability: '可持续',
  'Text formatting': '文本格式',
  'Time & calendar': '时间与日历',
  Tools: '工具',
  Transportation: '交通',
  Travel: '旅行',
  Weather: '天气',
};

const categoryNameMap: Record<string, string> = {
  accessibility: '无障碍',
  account: '账号与访问',
  animals: '动物',
  arrows: '箭头',
  buildings: '建筑',
  charts: '图表',
  communication: '沟通',
  connectivity: '连接',
  cursors: '光标',
  design: '设计',
  development: '编码与开发',
  devices: '设备',
  emoji: '表情',
  files: '文件',
  finance: '金融',
  'food-beverage': '餐饮',
  gaming: '游戏',
  home: '家居',
  layout: '布局',
  mail: '邮件',
  math: '数学',
  medical: '医疗',
  multimedia: '多媒体',
  nature: '自然',
  navigation: '导航与地点',
  notifications: '通知',
  people: '人物',
  photography: '摄影',
  science: '科学',
  seasons: '季节',
  security: '安全',
  shapes: '形状',
  shopping: '购物',
  social: '社交',
  sports: '运动',
  sustainability: '可持续',
  text: '文本格式',
  time: '时间与日历',
  tools: '工具',
  transportation: '交通',
  travel: '旅行',
  weather: '天气',
};

export function localizeCategoryTitle(title: string) {
  return categoryTitleMap[title] ?? title;
}

export function localizeCategoryName(name: string) {
  return categoryNameMap[name] ?? name;
}
