name: YCloud Icons React Native Checks

on:
  push:
    branches:
      - next
  pull_request:
    paths:
      - packages/icons-react-native/**
      - packages/icons-shared/**
      - tools/build-icons/**
      - tools/rollup-plugins/**
      - pnpm-lock.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm --filter @ycloud-web/icons-react-native build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test
        run: pnpm --filter @ycloud-web/icons-react-native test
