name: Linting PR

on:
  pull_request:
    paths:
      - '**/*.js'
      - '**/*.mjs'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.html'
      - '**/*.css'
      - '**/*.scss'
      - '**/*.json'
      - '**/*.yml'
      - '**/*.yaml'
      - .oxfmtignore
      - package.json
      - pnpm-lock.yaml
      - pnpm-workspace.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Get changed business icon files
        id: changed-business-icons
        uses: tj-actions/changed-files@v47
        with:
          files: |
            business-icons/**/*.svg
            business-icons/**/*.json

      - name: Run Linter
        run: |
          pnpm lint:es
          pnpm lint:format
          pnpm lint:svg:icons
          if [[ "${{ steps.changed-business-icons.outputs.any_changed }}" == "true" ]]; then
            pnpm lint:svg:business
          fi
          pnpm lint:json
