name: YCloud font checks

on:
  push:
    branches:
      - next
    paths:
      - .github/actions/setup-pnpm/**
      - packages/icons-static/package.json
      - .github/workflows/ycloud-font.yml
      - tools/build-font/**
  pull_request:
    paths:
      - .github/actions/setup-pnpm/**
      - .github/workflows/ycloud-font.yml
      - packages/icons-static/package.json
      - tools/build-font/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ycloud-font:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Execute unit tests for build-font
        run: pnpm test:font

      - name: Create font in packages/icons-static/font
        run: pnpm build:font

      - name: 'Upload to Artifacts'
        uses: actions/upload-artifact@v7
        with:
          name: ycloud-font
          path: packages/icons-static/font
          retention-days: 3
